RedRoverSchool/OpenWeatherPython_06

tests/test_group_pythonista.py
=> New file for pythonista

tests/test_group_pythonista.py
=> New test added Olga

tests/test_group_ducktales.py
=> Added check page title test

tests/snake_oil_group.py
add 2 tests for the Search City field:
test_search_field_present
test_search_field_placeholder
=> add tests for search city field

tests/test_group_pythonista.py
@KatyaMy Please approve my request
=> New update

tests/test_the_hardworking_club.py
=> Test iuliia patriarkh

tests/test_pandoras_box.py
=> created test_pandoras_box

tests/test_group_ducktales.py
Were added two test for verification than status API key was changed after approve and not was changed after skip. 
- test_status_api_key_changed
- test_status_api_key_not_changed
=> feat: two tests - change status API keys added

tests/test_group_roma.py
First test for group_roma. 
Test work with github.
=> Add test for group_roma

tests/snake_oil_group.py
=> add new test logo presented

tests/test_no_group_ArinaJur.py
Add
test_default_city
test_default_units
test_city_name_changed_as_expected_after_search
=> Add tests: Default city, Default units, search new city

tests/test_group_future_Auto_QA.py
=> ADD: test homePage Header

tests/test_the_hardworking_club.py
=> feat: add test check_title_mp_page & new branch

tests/test_the_hardworking_club.py
Please review and approve if everything is ok
=> feat: add test top bar visual

tests/test_the_hardworking_club.py
=> Test eayrapetyan test_top_bar_guide

tests/test_the_hardworking_club.py
=> feat: add test support drop down

tests/test_the_hardworking_club.py
Please check test and approve.
=> feat: add test pricing title

tests/test_the_hardworking_club.py
=> feat: add test_partners_title

tests/test_group_pythonista.py
@verafes @TetianaB @aigulmustafina
=> added test tab dashboard

tests/test_group_ducktales.py
Hi! This is my test project. It would be a pleasure to get a review from you. Thank you so much!
=> Test regev rita

tests/test_group_ducktales.py
Здравствуйте, Айгуль! Я переписала часть кода с регулярными выражениями)
=> Test rita regev: добавлены регулярные выражения

tests/test_group_pythonista.py
@KatyaMy @verafes Please approve
=> Test tanya 4

tests/test_pandoras_box.py
tests added:
- test_sing_in_empty_fields
- test_sing_in_positive
- test_open_weather_map
- test_current_weather_api
=> tests added:

tests/test_group_pythonista.py
@KatyaMy @verafes  Please approve another one I hope it will work also
=> New tc for Guide tab title

tests/test_group_pythonista.py
@verafes @TetianaB @aigulmustafina
=> fixed selectors

tests/test_the_hardworking_club.py
=> feat: add 2 tests mp page

tests/test_group_pythonista.py
=> added_new_test about us

tests/test_group_pythonista.py
@verafes @TetianaB @irench @aigulmustafina
=> added fixture, test fixed

tests/test_group_future_Auto_QA.py
verify the presence of a placeholder in the email field in SingIn form
@KatyaMy @ArinaJur @aigulmustafina @DionisIno
=> test should be placeholder in email field

tests/test_group_pythonista.py
@verafes @TetianaB @aigulmustafina
=> added new test About_US page spec

tests/test_group_pythonista.py
=> New tc for search_fild pythonista

tests/test_group_pythonista.py
@KatyaMy @verafes Please approve
=> pythonista new tc for Support tab

tests/test_group_pythonista.py
@verafes @TetianaB @aigulmustafina @Eliser14
=> fixed tests(relax)

test_group_moon_cat.py
=> added test_open_page #1

tests/test_group_pythonista.py
@verafes @TetianaB @aigulmustafina
=> added test_visability_Copyright and new fixture for cookies panel

tests/test_group_pythonista.py
=> test_should_refresh_link

tests/test_group_dinovo.py
I have this new stuff I want to merge. What do you all think about it?
=> Test vicniciana

tests/test_group_snake_oil.py
add waiter presence of element located
=> add waiter presence of element located

tests/test_group_ducktales.py
Добрый вечер, Айгуль! Очень буду рада, если посмотрите мой второй тест)
=> Добавила тест, сравнивающий значения температуры с веб-страницы со значениями из api

tests/test_thehardworking_club.py
=> TC_001.09.04 | Main page > Widgets constructor > Confirm "Your API Key” and “ Your City Name” fields are visible

tests/test_group_pythonista.py
@aigulmustafina @verafes @KatyaMy Please approve if it's PASS here
=> TC_002.03.05 | Header > Links > Navigation > Dashboard link is clickable and visible

tests/test_pandoras_box.py
TC_002.01.03 > Header > Logo > Verify Logo is visible from all pages specified in data
https://trello.com/c/ib14hPf6
=> TC_002.01.03 > Header > Logo > Verify Logo is visible from all pages specified in data

tests/test_group_snake_oil.py
added test_tc_003_10_06_verify_linkedIn_link_is_visible
[https://trello.com/c/gVOxTSKK](url)
=> AT_003.10.06 | Footer > Footer > Social media module > Icons-links visibility and сlickability > Verify the LinkedIn link is visible

tests/test_group_snake_oil.py
=> AT_003.10.08|Footer > SM module > Verify clickability of LinkedIn-link

tests/test_thehardworking_club.py
=> TC_001.09.07 | <Main page > Widgets constructor > Interacting with widgets' selection> Verify display of bottom widget 1 for Selected Type

tests/test_group_pytest.py
=> AT_006.02.02 | Weather Dashboard > "How to start" block > Verify all(7) links are visible

tests/test_group_no_pain_no_gain.py
TC_002.01.01 | Header > Logo > Verify returning from Guide page to main page by clicking on Logo
https://trello.com/c/4bQN83db
=> TC_002.01.01 | Header > Logo > Verify returning from Guide page to main page by clicking on Logo

tests/test_group_pythonista.py
@aigulmustafina @verafes @KatyaMy  Please approve
=> TC_002.03.06 | Header > Links > Navigation > Dashboard link redirects to correct page

tests/test_group_pythonista.py
TC_006.02.01 | Weather Dashboard > How to star block> Verify display of How to Start section in Dashboard for non-signed-in user
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;s4dMO7ct&#x2F;289-at0060201-weather-dashboard-how-to-start-block-verify-display-of-how-to-start-section-in-dashboard-for-non-signed-in-user">AT_006.02.01 | Weather Dashboard &gt; &quot;How to start&quot; block&gt; Verify display of &quot;How to Start&quot; section in Dashboard for non-signed-in user</a></blockquote>
=> TC_006.02.01 | Weather Dashboard > How to star block> Verify display of How to Start section in Dashboard for non-signed-in user

tests/test_pandoras_box.py
=> TC_001.09.06 | Main page > Widgets constructor > Interacting with widgets' selection > Verify temperature switched on Fahrenheit

tests/test_group_ducktales.py
TC_003.09.01 | Footer > Download OpenWeather app module > Visibility, structure, links сlickability> The module title's display
=> TC_003.09.01 | Footer > Download OpenWeather app module > Visibility, structure, links сlickability> The module title's display

tests/test_pandoras_box.py
=> TC_002.02.01 | Header > Search field > Search city > Verify that search result contains requested city name

tests/test_group_trust_me_i_am_engineer.py
=> AT_001.05.01 | Main page > Search city widget > Weather for current location > Verify the current date and time

requirements.txt, tests/test_group_snake_oil.py
=> AT_006.02.04|Dashboard>"How to start" block>Verify links redirection

tests/test_group_trust_me_i_am_engineer.py
=> AT_005.04.01 | Weather API > Self > Page structure, functionality > Checking the title on the "Weather API" page

tests/test_group_future_auto_qa.py
AT_002.02.07 - https://trello.com/c/kpxfugxr
=> AT_002.02.07 | Header > Search field > Search city > Verify Placeholder is displayed in Search field

tests/test_group_pythonista.py
https://trello.com/c/Z45TcvS6
TC_002.01.04 | Header > Logo > Verify clicking on a logo from the Dashboard page redirects to the main page
=> TC_002.01.04 | Header > Logo > Verify clicking on a logo from the Dashboard page redirects to the main page

tests/test_group_ducktales.py
TC_001.04.03 | Main page > Search city widget > 8-day-forecast > Verify in day-list first element > day by week
=> AT_001.04.03 | Main page > Search city widget > 8-day-forecast 

tests/test_group_trust_me_i_am_engineer.py
=> AT_010.01.02 | Our Initiatives > Visibility, сlickability, correct redirection>Verify "Learn more" button is clickable

tests/test_pandoras_box.py
=> TC_001.01.02 | Main page > Search city widget > Search city > Verify input of city name in cyrillic

tests/test_group_future_auto_qa.py
AT - https://trello.com/c/ZkdBY5rn
=> AT_002.02.09 | Header > Search field > Search city > Verify Placeholder disappears when a symbol is typed in Search field

tests/test_thehardworking_club.py
Link to trello AT:
https://trello.com/c/XRyT2NOT/354-at0010902-main-page-widgets-constructor-verify-that-3-widget-types-are-presented-on-the-page
Please review
=> AT_001.09.02 | Main page > Widgets constructor > Verify that 3 widget types are presented on the page

tests/test_group_ducktales.py
AT [https://trello.com/c/5779D9Ma/391-at010010101-our-initiatives-verify-the-presence-of-our-initiatives-section](url)
TC [https://trello.com/c/TtZjb0LD/290-tc010010101-our-initiatives-verify-the-presence-of-our-initiatives-section](url)
=> TC_010.01.01_01 | Our Initiatives > Verify the presence of 'Our Initiatives' section

tests/test_group_ducktales.py
AT_001.04.04 | Main page > Search city widget > 8-day-forecast > Verify in day-list first element > month
=> AT_001.04.04 | Main page > Search city widget > 8-day-forecast > Verify in day-list first element > month

tests/test_group_pythonista.py
TC_006.02.03 | Weather Dashboard > Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IBbIkswT&#x2F;454-at0060203-weather-dashboard-verify-the-transition-to-another-page-when-clicking-on-the-button-try-the-dashboard-for-non-signed-i">AT_006.02.03 | Weather Dashboard &gt; Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user</a></blockquote>
=> AT_006.02.03 | Weather Dashboard > Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user

tests/test_group_snake_oil.py
=> TC_003.04.01 | Footer > Technologies module > Verify the Technologies module title is visible on each page

tests/test_group_trust_me_i_am_engineer.py
=> AT_007.02.01 | Marketplace > Create New History Bulk > Visibility, clickability, search > Verify the method of input location

tests/test_pandoras_box.py
https://trello.com/c/LXb7Zk9b/257-tc0100104-our-initiatives-visibility-%D1%81lickability-correct-redirection-verify-correct-redirection
=> TC_010.01.04 | Our Initiatives > Visibility, сlickability, correct redirection > Verify correct redirection

tests/test_group_bugs_in_each_step.py
https://trello.com/c/PuC0SQ0l/441-at0031204-footer-link-navigation-product-collections-module-current-and-forecast-apis-link-functionality
=> AT_003.12.04 | Footer > Link navigation | Product Collections module > Current and Forecast APIs link functionality

tests/test_pandoras_box.py
=> TC_006.01.05 | Weather Dashboard > Description > Visibility of image in module

tests/test_group_roma.py
=> AT_003.01.01 | Footer > Visibility and website identification > Verify Footer is visible from all pages specified in data

tests/test_group_trust_me_i_am_engineer.py
=> AT_001.05.02 | Main page > Search city widget > Weather for current location > Verify current location (city name)

tests/test_pandoras_box.py
=> TC_006.04.04 | Weather Dashboard > Pricing and limits > Verify that different pricing plans are visible

test_group_100000.py
Test verifying humidity percentage in detailed weather data  for current location added
https://trello.com/c/pKQYbSFA
=> AT_001.05.03 | Main page >Search city widget >Verify humidity percentage in detailed weather data for current location

tests/test_group_pythonista.py
TC_005.06.01 | Weather API > Climatic forecast 30 days > Visibility ‘Climatic forecast 30 days’ page title
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;regjQFhU&#x2F;597-at0050601-weather-api-climatic-forecast-30-days-visibility-climatic-forecast-30-days-page-title">AT_005.06.01 | Weather API &gt; Climatic forecast 30 days &gt; Visibility ‘Climatic forecast 30 days’ page title</a>
=> AT_005.06.01 | Weather API > Climatic forecast 30 days > Visibility ‘Climatic forecast 30 days’ page title

tests/test_group_ducktales.py
AT_003.09.02: https://trello.com/c/ajYJxb8C/588-tc0030902-footer-download-openweather-app-module-visibility-structure-links-%D1%81lickability-download-on-the-app-store-brand-link-di
TC_003.09.02: https://trello.com/c/UnFW2rXr/92-footer-download-openweather-app-module-visibility-structure-links-%D1%81lickability-download-on-the-app-store-brand-link-display
=> AT_003.09.02| Footer > Download OpenWeather app module > Visibility, structure, links сlickability> Download on the App Store brand-link display

tests/test_group_pytest.py
=> AT_008.01.04 | Pricing > Self> Page structure, functionality>Check 6 sections are visible

tests/test_group_optimists_of_rationality_middle_devs.py
https://trello.com/c/E9NtwoMs - Trello Link
=> AT_001.02.02_01 | Main page > Search city widget > Verify temperature switched to the Imperial system

tests/test_group_trust_me_i_am_engineer.py
ERR | Fix code > test_TC_001_04_06_1_verify_visibility_of_week_days_in_8_days_forecast
https://trello.com/c/IDGp0NZA
=> ERR | Fix code > test_TC_001_04_06_1

tests/test_pandoras_box.py
=> TC_001.09.05 | Main page > Widgets constructor > Interacting with widgets' selection > Verify temperature switched on Celsius

tests/test_group_pytest.py
=> AT_003.10.07 | Footer > Social media module > Icons-links visibility and сlickability > Verify the visibility of Medium icon-link

tests/test_pandoras_box.py
AТ_002.02.06 | Header > Search field > Search city> Verify closing of "Not found" notification
https://trello.com/c/86NMpnSk/626-ac0020206-header-search-field-search-city-verify-closing-of-not-found-notification
TC_002.02.06 | Header > Search field > Search city> Verify closing of "Not found" notification
https://trello.com/c/5Ydd1J9X/170-tc0020206-header-search-field-search-city-verify-closing-of-not-found-notification
=> TC_002_02_06_verify_closing_of_NotFound_notification

tests/test_group_pythonista.py
TC_003.11.02 | Footer > Copyright >Visibility, Content> Verify the copyright information is present on the site page
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Mt6Q2fbz&#x2F;645-at0031102-footer-copyright-visibility-content-verify-the-copyright-information-is-present-on-the-site-page">AT_003.11.02 | Footer &gt; Copyright &gt;Visibility, Content&gt; Verify the copyright information is present on the site page</a></blockquote>
=> AT_003.11.02 | Footer > Copyright >Visibility, Content> Verify the copyright information is present on the site page

tests/test_group_trust_me_i_am_engineer.py
=> AT_007.02.03 | Marketplace > Create New History Bulk > Visibility, clickability, search > Verify search by coordinates

tests/test_group_optimists_of_rationality_middle_devs.py
https://trello.com/c/XQIMcYkL - Trello link
=> AT_006.03.01 | Weather Dashboard > Our users > Verify display of client logos

tests/test_group_optimists_of_rationality_middle_devs.py
https://trello.com/c/iXgtgWK2 - Trello link
=> AT_006.04.01 | Weather Dashboard > Pricing and limits > Verify display of "Pricing and limits" section

tests/test_group_ducktales.py
TC [https://trello.com/c/L6Y637Nl/342-tc010010202-our-initiatives-verify-the-functionality-of-our-initiatives-section](url)
AT [https://trello.com/c/fegvIpdO/389-at010010202-our-initiatives-verify-the-functionality-of-our-initiatives-section](url)
=> AT_010.01_02_02 | Our Initiatives > Verify the functionality of 'Our Initiatives' section

tests/test_pandoras_box.py
=> AT_010.01.01_1 | Our Initiatives > Visibility, сlickability, correct redirection > Verify button "Learn more", visibility, text on the button

tests/test_group_trust_me_i_am_engineer.py
https://trello.com/c/yGlK1WEp/145-tc0031209-footer-link-navigation-verify-pricing-link-leads-to-a-correct-page
=> AT_003.12.09 | Footer > Link navigation > Verify Pricing link leads to a correct page

tests/test_group_optimists_of_rationality_middle_devs.py
https://trello.com/c/oQtL84Wr - Trello link
=> AT_006.04.03 | Weather Dashboard > Pricing and limits >Verify that the "Subscribe" button is clickable in the "Pricing and limits" section

tests/test_group_trust_me_i_am_engineer.py
=> RF | AT_007.02.02 | Marketplace > Create New History Bulk > Visibility, clickability, search > Verify search by location name

tests/test_group_optimists_of_rationality_middle_devs.py
https://trello.com/c/n1AUv2zq - Trello link
=> AT_006.04.02 | Weather Dashboard > Pricing and limits >Verify that the "Sign up" button is clickable in the "Pricing and limits" section

tests/test_group_ducktales.py
AT_017.04.01:https://trello.com/c/krvjRZTM/687-at0170401-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-create-api-key-module-is-visible
TC_017.04.01: https://trello.com/c/wUUqV0F4/503-tc0170401-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-create-api-key-module-is-visible
=> AT_017.04.01| API Keys tab>Creating API Key >Visibility, clickability, creating>Verify that the "Create API Key" module is visible.

tests/test_group_trust_me_i_am_engineer.py
https://trello.com/c/ibZXwASr/686-at008010301-pricing-self-page-structure-functionality-check-a-visibility-of-pricing-page-title
=> AT_008.01.03_01 | Pricing > Self> Page structure, functionality > check a visibility of ‘Pricing’ page title

tests/test_group_pythonista.py
https://trello.com/c/0LzFjQga
TC_002.01.08 | Header > Logo > Verify logo from the Weather model page redirects to the main page
=> TC_002.01.08 | Header > Logo > Verify logo from the Weather model page redirects to the main page

tests/test_group_pythonista.py
TC_005.08.03 | Road Risk API >Visibility of Road Risk API Concept section
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wrlXMde2&#x2F;691-at0050803-road-risk-api-visibility-of-road-risk-api-concept-section">AT_005.08.03 | Road Risk API &gt;Visibility of &quot;Road Risk API Concept&quot; section</a></blockquote>
=> TC_005.08.03 | Road Risk API >Visibility of Road Risk API Concept section

tests/test_thehardworking_club.py
=> AT_006.01.12 | Weather Dashboard > Description > Verify ‌full description of weather dashboard

tests/test_group_100_000.py, tests/test_group_pythonista.py
TC_005.08.04 | Road Risk API > Redirection to the "How to request Road Risk API" section of the page
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4QPH5s69&#x2F;704-at0050804-road-risk-api-redirection-to-the-how-to-request-road-risk-api-section-of-the-page">AT_005.08.04 | Road Risk API &gt; Redirection to the &quot;How to request Road Risk API&quot; section of the page</a></blockquote>
=> AT_005.08.04 | Road Risk API > Redirection to the How to request Road Risk API section of the page

tests/test_group_ducktales.py
TC[https://trello.com/c/4uC3HjzE/288-tc0100208-our-initiatives-student-initiative-verify-the-visibility-of-faq-question-titles](url)
AT[https://trello.com/c/AY5qeR0B/390-at0100208-our-initiatives-student-initiative-verify-the-visibility-of-faq-question-titles](url)
=> AT_010.02.08 | Our Initiatives > Student initiative > Verify the visibility of FAQ question titles

tests/test_group_pythonista.py
https://trello.com/c/1PX94Jra
TC_002.03.16 | Header > Links > Navigation > Verify API link redirects to the Weather API page
=> AT_002.03.16 | Header > Links > Navigation > Verify API link redirects to the Weather API page

tests/test_group_moon_cat.py
https://trello.com/c/AjLp5KSB/727-at0050507-weather-api-daily-forecast-16-days-visibility-and-clickability-weather-fields-in-api-response-link
=> AT_005.05.07 | Weather API > Daily forecast 16 days > Visibility and clickability 'Weather fields in API response' link

tests/test_group_ducktales.py
TC [https://trello.com/c/oMfc5qls/741-tc0100209-our-initiatives-student-initiative-verify-the-clickability-of-faq-question-titles](url)
AT [https://trello.com/c/jJD5O3uE/743-at0100209-our-initiatives-student-initiative-verify-the-clickability-of-faq-question-titles](url)
=> AT_010.02.09 | Our Initiatives > Student initiative > Verify the clickability of FAQ question titles

tests/test_pandoras_box.py
=> AT_010.02.02 | Our Initiatives > Student initiative > Visibility of title Free Data for Students

tests/test_group_snake_oil.py
=> TC_003.04.02 | Footer > Technologies module > Verify that all links under Technologies module tab are visible and clickable

tests/test_group_pythonista.py
https://trello.com/c/Kc3WNp0Q
AT_002.01.09 | Header > Logo > Verify logo redirects from the Accuracy and quality of weather data page to the main page
=> AT_002.01.09 | Header > Logo > Verify logo redirects from the Accuracy and quality of weather data page to the main page

tests/test_group_pythonista.py
https://trello.com/c/OFsOebQf
TC_002.03.15 | Header > Links > Navigation > Verify API link is visible and clickable
=> AT_002.03.15 | Header > Links > Navigation > Verify API link is visible and clickable

tests/test_pandoras_box.py
=> AT_008.03.01 | Pricing >Current weather and forecast collection> Visibility, clickability of the Button "Detailed pricing"

tests/test_group_trust_me_i_am_engineer.py
https://trello.com/c/KVtJK71B/688-at0030804-footer-singl-links-set-links-visibility-and-clickability-verify-the-link-openweather-for-business-is-visible
=> AT_003.08.04 | Footer > Singl links set > Links visibility and clickability > Verify the link OpenWeather for Business is visible

tests/test_thehardworking_club.py
=> AT_006.05.04 | Weather Dashboard > "Contact Us" button leads to the correct page

tests/test_group_moon_cat.py
AT_005.05.02 | Weather API > Daily forecast 16 days > Redirect to the "Call 16 day / daily forecast data" section of the page
https://trello.com/c/9pr7zR2w/712
=> AT_005.05.02 | Weather API > Daily forecast 16 days > Redirect to the "Call 16 day / daily forecast data" section of the page

tests/test_thehardworking_club.py
=> AT_001.14.01 | Main Page > Navigation arrow > Visibility, clickability, functionality > Verify functionality of navigation arrow button

tests/test_group_snake_oil.py
=> TC_001.15.03 | Main page > OpenWeather global services (About us) > Verify redirection to About us page

tests/test_group_moon_cat.py
=> AT_005.04.07 | Weather API > Self > Page structure, functionality> Verify "sign up" link is visible and clickable

tests/test_group_snake_oil.py
[https://trello.com/c/dz8J54Vo](url)
=> AT_006.02.05|WeatherDashboard>How to start>Verify links redirection(signIn)

tests/test_group_100000/locators/marketplace_page_locators.py, tests/test_group_100000/pages/marketplace_page.py, tests/test_group_100000/tests/test_marketplace.py
=> RF_TC_007_01_01_Select_state_from_dropdown_list

tests/test_group_roma.py
=> TC_001.06.01 | Main page >Search city widget >Map with current weather > Redirect to Interactive World Weather Map

tests/test_group_trust_me_i_am_engineer.py, tests/test_group_trust_me_i_am_engineer/tests/main_page_test.py
=> RF_AT_001.02.02 | Main page > Search city widget > Switching temperature measuring system > Verify temperature switched on imperial system

tests/test_group_moon_cat.py
Professional collections section>Verify "Learn more" link is visible and clickable
https://trello.com/c/BqnUkq0o
=> AT_005.04.08 | Weather API > Self > Page structure, functionality>

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/main_page_test.py
=> RF_AT_001.05.01 | Main page > Search city widget > Weather for current location > Verify the current date and time

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/marketplace_page.py, tests/test_group_trust_me_i_am_engineer/tests/marketplace_page_test.py
=> RF_AT_007.02.01 | Marketplace > Create New History Bulk > Visibility, clickability, search > Verify the method of input location

tests/test_group_moon_cat.py
Current & Forecast weather data collection section> Verify the "API doc" button is visible and clickable
https://trello.com/c/cIIDBHDe
=> AT_005.04.09 | Weather API > Self > Page structure, functionality>

pages/base_page.py, tests/test_group_100000/locators/dashboard_page_locators.py, tests/test_group_100000/pages/dashboard_page.py, tests/test_group_100000/tests/test_dashboard.py
RF_AT_006.02.01 | Weather Dashboard > "How to start" block> Verify display of "How to Start" section in Dashboard for non-signed-in user
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sJBS6OYo&#x2F;833-rfat0060201-weather-dashboard-how-to-start-block-verify-display-of-how-to-start-section-in-dashboard-for-non-signed-in-user">RF_AT_006.02.01 | Weather Dashboard &gt; &quot;How to start&quot; block&gt; Verify display of &quot;How to Start&quot; section in Dashboard for non-signed-in user</a></blockquote>
=> RF_AT_006.02.01 |Weather Dashboard>How to start block> Verify displayof How to Start section in Dashboard for non-signed-in user

tests/test_group_moon_cat.py
Current & Forecast weather data collection section> Verify the "Subscribe" button is visible and clickable
https://trello.com/c/yDc68AcW
=> AT_005.04.10 | Weather API > Self > Page structure, functionality>

tests/test_group_snake_oil/links/all_links.py, tests/test_group_snake_oil/locators/main_page_locators.py, tests/test_group_snake_oil/pages/main_page.py, tests/test_group_snake_oil/tests/test_main_page.py
=> RF_AT_003.10.06|Footer>SM>Icons-links visibility>Verify LinkedIn is visible

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/base_page.py, tests/test_the_hardworking_club/pages/widgets_page.py, tests/test_the_hardworking_club/tests_my/test_widgets_elements.py
=> RF_AT_001.09.04 | Main page > Widgets constructor > Confirm "Your API Key” and “ Your City Name” fields are visible

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/widgets_page.py, tests/test_the_hardworking_club/tests_my/test_widgets_elements.py
=> RF TC_001_09_02_verify_that_3_widgets_are_displayed

tests/test_group_snake_oil/links/all_links.py, tests/test_group_snake_oil/pages/main_page.py, tests/test_group_snake_oil/tests/test_main_page.py
=> RF_AT_003.10.08|Footer>SM>Icons сlickability>Verify LinkedIn is clickable

tests/test_group_snake_oil/links/all_links.py, tests/test_group_snake_oil/locators/footer_locators.py, tests/test_group_snake_oil/pages/footer.py, tests/test_group_snake_oil/tests/test_footer.py
=> RF_AT_003.04.01 | Footer > Technologies module > Verify the Technologies module title is visible on each page

tests/test_group_future_auto_qa/locators/main_page_locators.py, tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
RF - https://trello.com/c/n68VkpVS
=> RF | 002.02.07 | Header > Search field > Search city > Verify Placeholder is displayed in Search field

tests/test_group_future_auto_qa/locators/for_business_page_locators.py, tests/test_group_future_auto_qa/pages/for_business_page.py, tests/test_group_future_auto_qa/tests/for_business_page_test.py
AT [https://trello.com/c/xI5I5lzI/839-at0120104-for-business-products-verify-the-headings-are-present-on-the-page](url)
=> AT_012.01.04 | For Business > Products > Verify the headings are present on the page

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/locators/sign_in_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/pages/sign_in_page.py, tests/test_group_bugs_in_each_step/test_data/urls.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py, tests/test_group_bugs_in_each_step/tests/test_sign_in_page.py
https://trello.com/c/flNmtXlm/854-at0140301-sign-in-functionality-for-an-unregistered-user-checking-the-registration-question-display
=> AT_014.03.01 | Sign in  > Functionality for an unregistered user > Checking the registration question display

tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
RF - https://trello.com/c/Vmbrpk3B
=> RF | 002.02.09 | Header > Search field > Placeholder disappears if a symbol is typed in Search field

tests/test_group_100000/pages/marketplace_page.py, tests/test_group_100000/tests/test_marketplace.py
=> RF_TC_007_01_02_Select_year_from_dropdown_list

tests/test_group_100000/locators/marketplace_page_locators.py, tests/test_group_100000/pages/marketplace_page.py, tests/test_group_100000/tests/test_marketplace.py
=> RF_AT_007_01_03_Verify_Weather_parameters_to_be_provided

tests/test_thehardworking_club.py
=> AT_021_01_2 Main page > Agriculture analytics > Link Agriculture analytics is clickable

tests/test_group_100000/locators/marketplace_page_locators.py, tests/test_group_100000/tests/test_marketplace.py
=> RF_AT_007_01_04_Verify_Units_of_measurement

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/main_page_test.py
https://trello.com/c/vPqlXoQ9
move locators from MainPage to LocatorsPage
delete extra folder trust_me_i_am_engineer
=> RF | AT test_TC_001_04_06_1

tests/test_group_ducktales/locators/sign_in_locators.py, tests/test_group_ducktales/pages/API_keys_page.py, tests/test_group_ducktales/pages/sign_in_page.py, tests/test_group_ducktales/test_data/api_keys_page_data.py, tests/test_group_ducktales/test_data/sign_in_page_data.py, tests/test_group_ducktales/tests/test_API_keys_page.py
RF_AT_017.04.01: https://trello.com/c/O1rYRxRZ/867-rfat0170401-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-create-api-key-module-is-visible
=> RF_AT_017.04.01| API Keys tab>Creating API Key >Visibility, clickability, creating>Verify that the "Create API Key" module is visible.

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_road_risk_api.py
AT_005.08.01 | Road Risk API >Verify Page Title for Road Risk API
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;h3G9vrpo&#x2F;872-at0050801-road-risk-api-verify-page-title-for-road-risk-api">AT_005.08.01 | Road Risk API &gt;Verify Page Title for Road Risk API</a></blockquote>
not RF test
=> AT_005.08.01 | Road Risk API >Verify Page Title for Road Risk API

tests/test_group_zmeyki.py
https://trello.com/c/YzezlKSu/226-tc0010802-main-page-search-city-widget-information-about-humidity-winds-speed-visibility-and-temperature
=> AT_001.08.02 | Main Page > Search city > Information about weather items is visible.

tests/test_group_100000/locators/dashboard_page_locators.py, tests/test_group_100000/pages/dashboard_page.py, tests/test_group_100000/tests/test_dashboard.py
RF_AT_006.02.03 | Weather Dashboard > Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;giq55MZ4&#x2F;887-rfat0060203-weather-dashboard-verify-the-transition-to-another-page-when-clicking-on-the-button-try-the-dashboard-for-non-signed">RF_AT_006.02.03 | Weather Dashboard &gt; Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user</a></blockquote>
=> RF_AT_006.02.03 | Weather Dashboard > Verify the transition to another page when clicking on the button [Try the Dashboard], for non-signed-in user

pages/base_page.py, tests/test_group_snake_oil/links/all_links.py, tests/test_group_snake_oil/locators/dashboard_locators.py, tests/test_group_snake_oil/pages/dashboard_page.py, tests/test_group_snake_oil/test_data/dashboard_page_data.py, tests/test_group_snake_oil/tests/test_dashboard_page.py
=> RF_AT_006.02.04|Dashboard>How to start>Verify links redirection signed out

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/test_data/urls.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/d6IAz7mG/888-at0030303-footer-product-collections-module-historical-weather-data-link-visibility
=> AT_003.03.03 | Footer > Product Collections module > Historical Weather Data link visibility

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/PuC0SQ0l/441-rfat0031204-footer-link-navigation-product-collections-module-current-and-forecast-apis-link-functionality
=> RF_AT_003.12.04 | Footer > Link navigation | Product Collections module > Current and Forecast APIs link functionality

tests/test_group_bugs_in_each_step.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/hgFN1UTs/577-rfat0030302-footer-product-collections-module-current-and-forecast-apis-link-сlickability
=> RF_AT_003.03.02 | Footer > Product Collections module > Current and Forecast APIs link сlickability

tests/test_pandoras_box/pages/header.py, tests/test_pandoras_box/test_data/header_data.py, tests/test_pandoras_box/tests/test_header.py
=> RF AT_002.01.03 | Header > Logo > Verify Logo is visible from all pages specified in data

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/mOKc2XwU/906-at0030304-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-weather-dashboard-link-visibility
=> AT_003.03.04 | Footer > Product Collections module > Visibility, structure, links сlickability > Verify Weather Dashboard link visibility

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/main_page_test.py, tests/test_old_group_trust_me_i_am_engineer.py
=> RF_AT_008.01.03_01 | Pricing > Self> Page structure, functionality > check a visibility of ‘Pricing’ page title

tests/test_group_future_auto_qa/locators/main_page_locators.py, tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
=> AT_002_03_23  | Header > Links > Navigation > Support > Verify that the FAQ link is visible and clickable

tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
=> AT_002.03.09_01 | Header > Links > Navigation > Support > Verify that FAQ submenu link opens the correct page

tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/jEAz8Z4G/919-at0031202-footer-link-navigation-verify-weather-dashboard-link-functionality
=> AT_003.12.02 | Footer > Link navigation > Verify Weather Dashboard link functionality

tests/test_group_100000/locators/marketplace_page_locators.py, tests/test_group_100000/pages/marketplace_page.py, tests/test_group_100000/tests/test_marketplace.py
=> RF_AT_007_01_06_Verify_amount_of_order

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/fSMtqaKa/920-at0031203-footer-link-navigation-verify-weather-maps-link-functionality
=> AT_003.12.03 | Footer > Link navigation > Verify Weather Maps link functionality

tests/test_pandoras_box/pages/widgets_constructor_page.py, tests/test_pandoras_box/tests/test_widgets_constructor_page.py
=> RF AT_001.09.05 | Main page > Widgets constructor > Interacting with widgets' selection > Verify temperature switched on Celsius

tests/test_group_lutz_squad/locators/main_page_locators.py, tests/test_group_lutz_squad/pages/__init__.py, tests/test_group_lutz_squad/pages/main_page.py, tests/test_group_lutz_squad/tests/test_main_page.py
https://trello.com/c/fybl3muM/640-at0031207-footer-link-navigation-about-us-link-leads-to-correct-page
=> RF_AT_003.12.07 | Footer > Link navigation > About us link leads to correct page

tests/test_group_qa_anna_prokhoda/links/links.py, tests/test_group_qa_anna_prokhoda/locators/main_page_locators.py, tests/test_group_qa_anna_prokhoda/locators/price_page_locators.py, tests/test_group_qa_anna_prokhoda/pages/main_page.py, tests/test_group_qa_anna_prokhoda/tests/test_main_page.py
=> RF_AT_002.03.07 | Header > Links > Navigation > The link "Marketplace" leads to the page "Marketplace"

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/widgets_page.py, tests/test_the_hardworking_club/tests_my/test_widgets_elements.py
=> RF | AT_001.09.04 | Main page > Widgets constructor > Verify visibility of Fahrenheit

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/weather_dashboard_page_1.py, tests/test_the_hardworking_club/tests/test_weather_dashboard.py, tests/test_thehardworking_club.py
=> RF | AT_006.05.04 | Weather Dashboard > "Contact Us" button leads to the correct page

tests/test_group_snake_oil/locators/footer_locators.py, tests/test_group_snake_oil/pages/footer.py, tests/test_group_snake_oil/tests/test_footer.py
=> RF_AT_003.04.02 | Footer > Technologies module > Verify that all links under Technologies module tab are visible and clickable

tests/test_group_ducktales/locators/our_initiatives_page_locators.py, tests/test_group_ducktales/pages/our_initiatives_page.py, tests/test_group_ducktales/test_data/our_initiatives_page_data.py, tests/test_group_ducktales/tests/test_our_initiatives_page.py
RF_AT [trello.com/c/EsrDApQX/930-rfat010010202-our-initiatives-verify-the-functionality-of-our-initiatives-section](https://trello.com/c/EsrDApQX/930-rfat010010202-our-initiatives-verify-the-functionality-of-our-initiatives-section)
=> RF_AT_010.01.02_02 | Our Initiatives > Verify the functionality of 'Our Initiatives' section

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py, tests/test_group_bugs_in_each_step_old.py
https://trello.com/c/oRTwD1lg/929-at0031208-footer-link-navigation-verify-our-technology-link-functionality
=> AT_003.12.08 | Footer > Link navigation > Verify Our technology link functionality

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py, tests/test_group_bugs_in_each_step_old.py
https://trello.com/c/WRV80oF9/936-at0031216-footer-link-navigation-verify-accuracy-and-quality-of-weather-data-link-functionality
=> AT_003.12.16 | Footer > Link navigation > Verify Accuracy and quality of weather data link functionality

tests/test_group_EPIC_team.py
AT_003.12.10 | Footer > Link navigation > Verify FAQ link leads to a correct page
link to Trello card
https://trello.com/c/0VgBDGuC/832-at0031210-footer-link-navigation-verify-faq-link-leads-to-a-correct-page
=> AT_003.12.10 | Footer > Link navigation > Verify FAQ link leads to a correct page

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/tPcYhI9e/938-at0031217-footer-link-navigation-verify-connect-your-weather-station-link-functionality
=> AT_003.12.17 | Footer > Link navigation > Verify Connect your weather station link functionality

tests/test_group_qa_anna_prokhoda/links/links.py, tests/test_group_qa_anna_prokhoda/pages/price_page.py, tests/test_group_qa_anna_prokhoda/tests/test_price_page.py
=> RF_AT_002.01.07 | Header > Logo > Verify clicking on the logo from page Pricing redirects to main page

tests/test_group_100000/locators/main_page_locators.py, tests/test_group_100000/pages/main_page.py, tests/test_group_100000/tests/test_main_page.py
RF_AT_003.05.03 | Footer > Subscription module >Visible, structure, links сlickability> Verify How to start - link is сlickable
=> RF_AT_003.05.03 Verify 'How to start' link is сlickable

tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
AT - https://trello.com/c/rjY8IOj8
=> AT_002.03.24 | Header > Links > Navigation > Support > How to Start submenu link is visible and clickable

tests/test_pandoras_box/pages/weather_conditions_page.py, tests/test_pandoras_box/tests/test_weather_conditions_page.py
=> RF_AT_001.12.05 | Main Page > Weather Conditions > Weather condition codes > Verify that Clouds group of codes is visible

tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
AT - https://trello.com/c/JfQq8H2n
=> AT_002.03.10_01 | Header > Links > Navigation > Support > How to Start submenu link opens the correct page

tests/test_group_ducktales/pages/main_page.py, tests/test_group_ducktales/test_data/main_page_data.py, tests/test_group_ducktales/tests/test_main_page.py
https://trello.com/c/tmeWRLsO/953-rfat0010404-main-page-search-city-widget-8-day-forecast-verify-in-day-list-first-element-month
=> RF_AT_001.04.04 | Main page > Search city widget > 8-day-forecast > Verify in day-list first element > month

tests/test_group_ducktales/locators/our_initiatives_page_locators.py, tests/test_group_ducktales/pages/our_initiatives_page.py, tests/test_group_ducktales/tests/test_our_initiatives_page.py
RF_AT https://trello.com/c/yu3Ybq5W/952-rfat0100208-our-initiatives-student-initiative-verify-the-visibility-of-faq-question-titles
=> RF_AT_010.02.08 | Our Initiatives > Student initiative > Verify the visibility of FAQ question titles

tests/test_group_100000/locators/pricing_page_locators.py, tests/test_group_100000/pages/pricing_page.py, tests/test_group_100000/tests/test_pricing.py
AT_008_02_02_Visibility_the_title_OneCall_is_visible
https://trello.com/c/MNKf3pSd
=> AT_008_02_02_Visibility_the_title_OneCall_is_visible

tests/test_group_zmeyki.py
https://trello.com/c/TptJttp9/358-tc0100207-our-initiatives-student-initiative-visibility-%D1%81lickability-correct-redirection-verify-that-the-link-in-the-third-item
=> AT_010.02.07 | Student initiative > Verify correct redirection to popup window

pages/base_page.py, tests/test_group_qa_anna_prokhoda/links/links.py, tests/test_group_qa_anna_prokhoda/locators/member_page_loc.py, tests/test_group_qa_anna_prokhoda/pages/member_page.py, tests/test_group_qa_anna_prokhoda/tests/test_member_page.py
попробую ещё раз с нуля закоммитить тест member_page
закинула все файлы в уже созданной Александрой папку группы
почистила лишние методы
=> AT_018.03.02 | Subscriptions >Subscribe to Developer > Subscription payment is available > Verify error messages appeared when submitting blank form

tests/test_pandoras_box/pages/main_page.py, tests/test_pandoras_box/pages/maps_page.py, tests/test_pandoras_box/tests/test_maps_page.py
=> RF_AT_002.01.06 | Header > Logo >Verify return to Main page from "Interactive weather maps"

tests/test_group_no_pain_no_gain/locators/footer_locators.py, tests/test_group_no_pain_no_gain/tests/test_footer.py
[RF_AT_003.08.07 | Footer > Singl links set > Links visibility and clickability > Verify Blog link is visible](https://trello.com/c/yWd6yZOo/676-rfat0030807-footer-singl-links-set-links-visibility-and-clickability-verify-blog-link-is-visible)
=> RF_AT_003.08.07 | Footer > Singl links set > Links visibility and clickability > Verify Blog link is visible

tests/test_group_ducktales/pages/our_initiatives_page.py, tests/test_group_ducktales/tests/test_our_initiatives_page.py
RF_AT https://trello.com/c/E5s2Xh3x/959-rfat0100209-our-initiatives-student-initiative-verify-the-clickability-of-faq-question-titles
=> RF_AT_010.02.09 | Our Initiatives > Student initiative > Verify the clickability of FAQ question titles

tests/test_pandoras_box/pages/widgets_constructor_page.py, tests/test_pandoras_box/tests/test_widgets_constructor_page.py
=> RF AT_001.09.06 | Main page > Widgets constructor > Interacting with widgets' selection > Verify temperature switched on Fahrenheit

tests/test_group_future_auto_qa/locators/main_page_locators.py, tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
https://trello.com/c/zSpCRTXH/995-at0030602-footer-terms-conditions-module-verify-terms-conditions-module-title-display
=> AT_003.06.02 | Footer > Terms & Conditions module > Verify Terms & Conditions module title display

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test.py
=> AT_tc_001_15_01_verify_correct_header_about_us_page

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/WXCGjwcd/1000-at0031219-footer-link-navigation-verify-subscribe-for-free-link-functionality-for-unauthorized-user
=> AT_003.12.19 | Footer > Link navigation > Verify Subscribe for free link functionality for unauthorized user

tests/test_group_roma/links.py, tests/test_group_roma/locators/locators.py, tests/test_group_roma/pages/api_page.py, tests/test_group_roma/tests/api_page_test.py
=> RF | AT_002.01.02 | Header > Logo > Verify returning from API page to main page by clicking on Logo

tests/test_group_future_auto_qa/locators/main_page_locators.py, tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/tests/main_page_test.py
https://trello.com/c/irXkRraK/1001-at0031220-footer-link-navigation-verify-blog-link-functionality
=> AT_003.12.20 | Footer > Link navigation > Verify Blog link functionality

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test.py
=> AT_tc_001_15_02_verify_image_beside_header_is_displayed

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/wtyvWc6S/1008-at0031221-footer-link-navigation-verify-openweather-for-business-link-functionality
=> AT_003.12.21 | Footer > Link navigation > Verify OpenWeather for Business link functionality

tests/test_group_future_auto_qa/locators/for_business_page_locators.py, tests/test_group_future_auto_qa/pages/for_business_page.py, tests/test_group_future_auto_qa/tests/for_business_page_test.py
AT https://trello.com/c/WIjJOgQz/1023-at0120106-for-business-products-verify-the-buttons-are-presented-on-the-page
=> AT_012.01.06 | For Business > Products > Verify the buttons are presented on the page

tests/test_group_future_auto_qa/locators/for_business_page_locators.py, tests/test_group_future_auto_qa/pages/for_business_page.py, tests/test_group_future_auto_qa/tests/for_business_page_test.py
AT https://trello.com/c/tT2GXtCh/1028-at0120107-for-business-products-verify-the-elements-are-presented-on-the-page
=> TC_012.01.07 | For Business > Products > Verify the elements are presented on the page

tests/test_group_future_auto_qa/pages/for_business_page.py, tests/test_group_future_auto_qa/tests/for_business_page_test.py
AT https://trello.com/c/RtmJMaer/1063-at0120108-for-business-products-verify-that-the-elements-presented-on-the-page-are-clickable
TC https://trello.com/c/Q81M0NwT/992-tc0120108-for-business-products-verify-that-the-elements-presented-on-the-page-are-clickable
=> TC_012.01.08 | For Business > Products > Verify that the elements presented on the page are clickable

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test.py
=> AT_001_15_05_verify_five_headers_on_the_page_about_us_footer

tests/test_pandoras_box/pages/student_initiative.py, tests/test_pandoras_box/tests/test_student_initiative.py
=> TC_010.02.05 | Our Initiatives > Student initiative > "Get access" link leads to authorization window if user didn't check-in

tests/test_group_ducktales/locators/API_keys_locators.py, tests/test_group_ducktales/pages/API_keys_page.py, tests/test_group_ducktales/tests/test_API_keys_page.py
AT_017.04.04: https://trello.com/c/UGF7Vrzw/1069-at0170404-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-generate-button-is-clickable
TC_017.04.04: https://trello.com/c/CupBGFA9/507-tc0170404-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-generate-button-is-clickable
=> AT_017.04.04| API Keys tab>Creating API Key >Visibility, clickability, creating>Verify that the "Generate" button is clickable.

tests/test_group_python_qa/locators/locators.py, tests/test_group_python_qa/pages/main_page_pqa.py, tests/test_group_python_qa/tests/test_main_page_pqa.py
=> RF_AT_001.04.01 | refactor with POM

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test.py
=> AT_001_15_07_verify_redirection_to_weather_category_blog_page

tests/test_the_hardworking_club/pages/price_page.py, tests/test_the_hardworking_club/tests/test_price_page.py
The target URL was changed according to Aigul's advise. Add def allow_all_cookies form base_page.
=> Fix: RF | AT_008.01.01| Pricing > Self> “Subscribe to One Call by Call” button redirects to Billing_Info page for unauthorized user

tests/test_group_roma/locators/locators.py, tests/test_group_roma/pages/footer.py, tests/test_group_roma/test_data/footer_data.py, tests/test_group_roma/tests/test_footer.py
=> RF_AT_003.01.01 | Footer > Visibility and website identification > Verify Footer is visible from all pages specified in data

tests/test_group_lutz_squad/locators/page_with_map_locators.py, tests/test_group_lutz_squad/pages/page_with_map.py, tests/test_group_lutz_squad/tests/test_page_with_map.py
https://trello.com/c/Or5ggQPg/1073-at0010603-main-page-search-city-widget-map-with-current-weather-verify-clickability-of-pressure-button
=> AT_001.06.03 Main page >Search city widget >Map with current weather > Verify clickability of Pressure button

tests/test_group_lutz_squad/locators/accuracy_and_quality_of_weather_data_page_locators.py, tests/test_group_lutz_squad/locators/main_page_locators.py, tests/test_group_lutz_squad/pages/accuracy_and_quality_of_weather_data_page.py, tests/test_group_lutz_squad/pages/main_page.py, tests/test_group_lutz_squad/tests/test_accuracy_and_quality_of_weather_data_page.py
https://trello.com/c/5Ykk3ds4/957-at0011703-main-page-accuracy-and-quality-of-weather-data-verify-visibility-of-picture-example-of-graphics-with-some-metrics
=> AT_001.17.03 | Main Page > Accuracy and quality of weather data > Verify visibility of picture – example of graphics with some metrics

tests/test_group_python_qa/locators/locators.py, tests/test_group_python_qa/pages/main_page_pqa.py, tests/test_group_python_qa/tests/test_main_page_pqa.py
=> RF_AT_021.01.01 | refactor with POM

tests/test_group_ducktales/locators/API_keys_locators.py, tests/test_group_ducktales/pages/API_keys_page.py, tests/test_group_ducktales/tests/test_API_keys_page.py
AT_017.04.05 :  https://trello.com/c/avfu1H2l/1088-at0170405-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-api-key-is-generated
TC_017.04.05 : https://trello.com/c/HMPjCf8E/508-tc0170405-api-keys-tabcreating-api-key-visibility-clickability-creatingverify-that-the-api-key-is-generated
=> AT_017.04.05| API Keys tab>Creating API Key >Visibility, clickability, creating>Verify that the API key is generated

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/pages/dashboard_page.py, tests/test_group_100000/tests/test_dashboard_100.py, tests/test_group_100000/tests/test_road_risk_api_100.py
AT_005.08.06  Road Risk API>Verify redirection to the page with API keys by clicking on the API Key tab
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;irroTlQE&#x2F;1115-at0050806-road-risk-api-verify-redirection-to-the-page-with-api-keys-by-clicking-on-the-api-key-tab">AT_005.08.06 | Road Risk API &gt;Verify redirection to the page with API keys by clicking on the &quot;API Key&quot; tab</a></blockquote>
=> AT_005.08.06  Road Risk API>Verify redirection to the page with API keys by clicking on the API Key tab

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_road_risk_api_100.py
AT_005.08.07 | Road Risk API >Verification of National Weather Warning Sources List
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5traD3Cc&#x2F;1117-at0050807-road-risk-api-verification-of-national-weather-warning-sources-list">AT_005.08.07 | Road Risk API &gt;Verification of National Weather Warning Sources List</a></blockquote>
=> AT_005.08.07 | Road Risk API >Verification of National Weather Warning Sources List

tests/test_group_snake_oil/links/all_links.py, tests/test_group_snake_oil/locators/student_initiative_page_locators.py, tests/test_group_snake_oil/pages/student_initiative_page.py, tests/test_group_snake_oil/tests/test_student_initiative_page_so.py
=> refactor AT_010.02.03

tests/test_group_roma/locators/locators.py, tests/test_group_roma/pages/footer.py, tests/test_group_roma/test_data/footer_data.py, tests/test_group_roma/tests/test_footer.py
=> RF_AT_003.01.02 | Footer > Visibility and website identification > Verify copyright is visible from all pages specified in data

tests/test_group_python_qa/pages/guide_page.py, tests/test_group_python_qa/tests/test_guide_page.py
=> RF | AT_004.08.02 | Refactor with POM

pages/base_page.py, tests/test_group_python_qa/locators/locators.py, tests/test_group_python_qa/pages/solar_api_pqa.py, tests/test_group_python_qa/tests/solar_api_pqa.py
=> RF_AT_005.10.03 | refactor with POM

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test.py
=> AT_001_15_10_verify_redirection_to_app_store

tests/test_group_future_auto_qa/locators/main_page_locators.py, tests/test_group_future_auto_qa/pages/main_page.py, tests/test_group_future_auto_qa/test_data/urls.py, tests/test_group_future_auto_qa/tests/suits_of_pages_test.py
https://trello.com/c/FoWCl2hc/1142-at0030806-footer-single-links-set-links-visibility-and-%D1%81lickability-verify-about-us-link-is-clickable-on-each-page-specified-in
=> AT_003.08.06 | Footer > Single links set > Links visibility and сlickability > Verify About us link is clickable on each page specified in Data

tests/test_group_100000/locators/marketplace_page_locators.py, tests/test_group_100000/pages/marketplace_page.py, tests/test_group_100000/tests/test_marketplace_100.py
https://trello.com/c/b6r0euW3/1084-at0070302-marketplace-create-new-history-forecast-bulk-visibility-clickability-search-verify-visibility-of-location-name-on-the
=> AT_007.03.02 | Marketplace > Create New History Forecast Bulk > Visibility, clickability, search > Verify visibility of location name on the map

tests/test_group_python_qa/links/links_all_pages.py, tests/test_group_python_qa/locators/locators.py, tests/test_group_python_qa/pages/main_page_pqa.py, tests/test_group_python_qa/tests/test_main_page_pqa.py
=> RF | AT_001.17.01 | Refactor according to POM

tests/test_group_python_qa/locators/locators.py, tests/test_group_python_qa/pages/solar_api_pqa.py, tests/test_group_python_qa/tests/test_solar_api_pqa.py
=> RF_AT_005.10.02 | refactor with POM

tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/pages/about_us_page.py, tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test_tmi.py
after_hovering_over_on_element
https://trello.com/c/gJxG69FA
=> AT_001_15_11_verify_cursor_transformation

tests/test_group_lutz_squad/locators/page_with_map_locators.py, tests/test_group_lutz_squad/pages/page_with_map.py, tests/test_group_lutz_squad/tests/test_page_with_map.py
[TC_001.06.02 | Main page >Search city widget >Map with current weather > Verify clickability of Cities checkbox](https://trello.com/c/2uVnlP3n)
=> AT_001.06.02 | Main page >Search city widget >Map with current weather > Verify clickability of Cities checkbox

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_api_page_100.py
=> RF_AT_008.02.04 Verify redirection One_Call_API_3 link

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/weather_dashboard_page_1.py, tests/test_the_hardworking_club/tests/test_weather_dashboard.py
=> RF test_TC_006_01_12_verify_weather_dashboard_full_description

tests/group_files/group_future_auto_qa.py, tests/test_group_future_auto_qa/locators/faq_page_locators.py, tests/test_group_future_auto_qa/pages/faq_page.py, tests/test_group_future_auto_qa/tests/faq_page_test.py
Refactoring to POM - https://trello.com/c/1H6WCag7
=> RF | 015.01.04 | Support > FAQ > Verify the hidden text is displayed by clicking on related heading

tests/test_the_hardworking_club/locators/locators_all.py, tests/test_the_hardworking_club/pages/widgets_page.py, tests/test_the_hardworking_club/tests/test_widgets_elements.py
=> RF test_TC_001_09_03_verify_visibility_of_celsius

tests/test_group_trust_me_i_am_engineer/pages/main_page.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test_tmi.py
=> RF_001_15_01 refactoring method "go_to_about_us_page"

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/locators/sign_in_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/pages/sign_in_page.py, tests/test_group_bugs_in_each_step/test_data/urls.py, tests/test_group_bugs_in_each_step/tests/test_sign_in_page.py, tests/test_group_bugs_in_each_step/tests/test_suits_of_pages.py
https://trello.com/c/PqWJDhVq/2123-at0140302-sign-in-functionality-for-an-unregistered-user-checking-the-link-to-the-registration-page-display
=> AT_014.03.02 | Sign in > Functionality for an unregistered user > Checking the link to the registration page display

tests/test_group_bugs_in_each_step/pages/sign_in_page.py, tests/test_group_bugs_in_each_step/test_data/urls.py, tests/test_group_bugs_in_each_step/tests/test_sign_in_page.py, tests/test_group_bugs_in_each_step/tests/test_suits_of_pages.py
https://trello.com/c/7rWwu0sv/2126-at0140303-sign-in-functionality-for-an-unregistered-user-checking-clickability-of-the-registration-link
=> AT_014.03.03 | Sign in > Functionality for an unregistered user | Checking clickability of the registration link

tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/pages/sign_in_page.py, tests/test_group_bugs_in_each_step/tests/test_sign_in_page.py, tests/test_group_bugs_in_each_step/tests/test_suits_of_pages.py
https://trello.com/c/EGOmGpb3/2128-at0140304-sign-in-functionality-for-an-unregistered-user-checking-the-link-in-the-sing-in-form-leads-to-the-registration-page
=> AT_014.03.04 | Sign in > Functionality for an unregistered user > Checking the link in the Sing In form leads to the registration page

tests/test_group_lutz_squad/locators/guide_page_locators.py, tests/test_group_lutz_squad/locators/links.py, tests/test_group_lutz_squad/pages/guide_page.py, tests/test_group_lutz_squad/tests/test_guide_page.py
=> AT_004.06.04 | Guide > Open weather products > Redirection to 'One Call API 3.0' page after click on the link 'One Call API by call'

pages/main_page.py, tests/test_pandoras_box/pages/search_result_page.py, tests/test_pandoras_box/tests/test_search_result_page.py
=> AT_001.05.04 | Main page >Search city widget >Weather for current location > Verify actual weather for current locatione

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py, tests/test_group_bugs_in_each_step/tests/test_suits_of_pages.py
https://trello.com/c/cq1SnVNO/2142-at0030603-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-website-terms-and-conditions-link-visibi
=> AT_003.06.03 | Footer > Terms & Conditions module > Visibility, structure, links сlickability > Verify Website terms and conditions link visibility

locators/locators.py, pages/about_us_page.py, pages/app_store_page.py, pages/blog_weather_category_page.py, pages/main_page.py, tests/test_about_us_page_ow6.py, tests/test_app_store_page_ow6.py, tests/test_blog_weather_category_page_ow6.py, tests/test_group_trust_me_i_am_engineer/locators/page_locators.py, tests/test_group_trust_me_i_am_engineer/tests/about_us_page_test_tmi.py, tests/test_main_page_ow6.py
https://trello.com/c/ixGVOSfK
https://trello.com/c/CDoOHSJD
https://trello.com/c/8sLjl9x8
https://trello.com/c/tXTuo8ur
https://trello.com/c/vmemBe1P
https://trello.com/c/gJxG69FA
=> RF_Final | tmi | ed

locators/locators.py, pages/main_page.py, pages/sign_in_page.py, test_data/urls.py, tests/test_main_page_ow6.py, tests/test_sign_in_page.py, tests/test_sign_in_page_ow6.py, tests/test_suits_of_pages_ow6.py
TC_003.03.03: https://trello.com/c/oG9LU4Gf/127-tc0030303-footer-product-collections-module-historical-weather-data-link-visibility
TC_003.03.04: https://trello.com/c/l6DvqhH7/128-tc0030304-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-weather-dashboard-link-visibility
TC_003.03.05: https://trello.com/c/pWsBsnsN/129-tc0030305-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-weather-dashboard-link-clickability
TC_003.06.03: https://trello.com/c/P4zSBFmF/2141-tc0030603-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-website-terms-and-conditions-link-visibi
TC_003.08.05: https://trello.com/c/Ra2JkIm3/1098-tc0030805-footer-single-links-set-links-visibility-and-%D1%81lickability-verif …
=> RF_Final | group_bugs_in_each_step | alena-krauchuk

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
[RF] - https://trello.com/c/n68VkpVS
=> RF_AT 002.02.07 | POM | Header > Search field > Verify Placeholder is displayed

tests/test_group_python_qa/pages/partners_page_pqa.py, tests/test_group_python_qa/tests/test_partners_page_pqa.py
…ty of the link "See library"
https://trello.com/c/zvhEcWwL
=> AT_011.09.02 | Partners and solutions > Go (golang) > Verify clickability of the link "See library"

tests/test_group_bugs_in_each_step/locators/main_page_locators.py, tests/test_group_bugs_in_each_step/pages/main_page.py, tests/test_group_bugs_in_each_step/tests/test_main_page.py
https://trello.com/c/5bLX1Ncp/2086-at0030306-footer-product-collections-module-widgets-link-clickability
=> AT_003.03.06 | Footer > Product Collections module > Widgets link clickability

tests/test_group_optimists_of_rationality_middle_devs/locators/dashboard_page_locators.py, tests/test_group_optimists_of_rationality_middle_devs/locators/main_page_locators.py, tests/test_group_optimists_of_rationality_middle_devs/pages/dashboard_page.py, tests/test_group_optimists_of_rationality_middle_devs/tests/dashboard_page_test.py, tests/test_group_optimists_of_rationality_middle_devs/tests/for_business_page_test.py
=> RF_AT_006.04.03 | Weather Dashboard > Pricing and limits >Verify that the "Subscribe" button is clickable in the "Pricing and limits" section

pages/marketplace_page.py, tests/test_marketplace_page_ow6.py
007.03.02: https://trello.com/c/SC0wsT3S/1323-at0070302-marketplace-create-new-history-forecast-bulk-visibility-clickability-search-verify-visibility-of-location-name-on-the
007.03.03: https://trello.com/c/cjN01aUN/1135-at0070303-marketplace-create-new-history-forecast-bulk-visibility-clickability-search-verify-clickability-of-button-add-location
=> RF_Final | group_100000 | elena_pozhydaieva

tests/test_group_100000/locators/main_page_locators.py, tests/test_group_100000/pages/main_page.py, tests/test_group_100000/tests/test_main_page_100.py
RF_AT_003.11.01 | Footer > Copyright >Visibility,Content Main Page Verify the copyright information is present on the site page
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ejlBSVAI&#x2F;1138-rfat0031101-footer-copyright-visibilitycontent-main-page-verify-the-copyright-information-is-present-on-the-site-page">RF_AT_003.11.01 | Footer &gt; Copyright &gt;Visibility,Content [Main Page]&gt; Verify the copyright information is present on the site page</a></blockquote>
=> RF_AT_003.11.01 | Footer > Copyright >Visibility,Content Main Page Verify the copyright information is present on the site page

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
Final RF - https://trello.com/c/7mX7EB85
=> RF AT_002.03.23 | Header > Links > Navigation > Support > FAQ submenu is visible and clickable

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_api_page_100.py
RF_AT_005.06.01 | Weather API > Climatic forecast 30 days > Visibility Climatic forecast 30 days page title
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GQchf1RW&#x2F;1139-rfat0050601-weather-api-climatic-forecast-30-days-visibility-climatic-forecast-30-days-page-title">RF_AT_005.06.01 | Weather API &gt; Climatic forecast 30 days &gt; Visibility ‘Climatic forecast 30 days’ page title</a>
=> RF_AT_005.06.01 | Weather API > Climatic forecast 30 days > Visibility Climatic forecast 30 days page title

tests/test_openagro_page_ow6.py, tests/test_solar_api_ow6.py
Just fixing failed tests due to creation of a new Links class by someone else
=>  ref: fix locator fail due to added new class

tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_api_page_100.py
RF_AT_005.06.02 | Weather API > Climatic forecast 30 days > Redirect to the "How to make an API call" section of the page
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fUZv1Gwc&#x2F;1140-rfat0050602-weather-api-climatic-forecast-30-days-redirect-to-the-how-to-make-an-api-call-section-of-the-page">RF_AT_005.06.02 | Weather API &gt; Climatic forecast 30 days &gt; Redirect to the &quot;How to make an API call&quot; section of the page</a></blockquote>
=> RF_AT_005.06.02 | Weather API > Climatic forecast 30 days > Redirect to the "How to make an API call" section of the page

locators/locators.py, pages/main_page.py, pages/partners_page.py, test_data/urls.py, tests/test_main_page_ow6.py, tests/test_partners_page_ow6.py
https://trello.com/c/wZERaCzx/2112-at0010804-main-page-search-city-widget-hourly-forecast-for-current-location-verify-chart-is-present
https://trello.com/c/VUA7eMaB/2111-at0111501-partners-and-solutions-apache-camel-verify-correctly-redirected-the-link-apache-camel
https://trello.com/c/k5cM1yzp/2113-at0111502-partners-and-solutions-apache-camel-verify-visibility-and-clickability-of-the-link-apache-camel
https://trello.com/c/ZEXgLrAL/1516-rfat0031212-footer-link-navigation-product-collections-module-widgets-link-functionality
https://trello.com/c/UIzqu3Dn/1337-rfat0031224-footer-link-navigation-product-collections-module-all-link-functionality
=> RF_Final | group_future_Auto_QA | Natalya_Mastyaeva

locators/locators.py, pages/pricing_page.py, tests/test_pricing_page_ow6.py
RF_Final | offer_100000 | Pricing_page | Irina_Irico
=> RF_Final | offer_100000 | Pricing_page | Irina_Irico

tests/test_group_ducktales/pages/main_page_d.py, tests/test_group_ducktales/tests/test_main_page_d.py
=> RF_AT_001.04.05 into group_ducktales 

tests/test_group_ducktales/pages/main_page_d.py, tests/test_group_ducktales/tests/test_main_page_d.py
per OOP requirements
https://trello.com/c/lB7eNoBA
=> RF_AT_001.04.06 into group_ducktales per OOP requirements

tests/test_group_100000/locators/main_page_locators.py, tests/test_group_100000/pages/main_page.py, tests/test_group_100000/tests/test_main_page_100.py
…y that the Cookies management module is visible
=> RF_AT_003.13.01 | Footer > Cookies management module > Verify that the Cookies management module is visible

locators/locators.py, pages/faq_page.py, pages/main_page.py, test_data/all_links.py, tests/test_faq_page_ow6.py, tests/test_main_page_ow6.py
[AT_015.01.04] - https://trello.com/c/ybs8HCEy
[AT_002.03.09_01] https://trello.com/c/TV2UKFfI
[AT_002.03.10_01] - https://trello.com/c/JfQq8H2n
=> RF_Final | future_auto_qa | Verafes

locators/locators.py, pages/our_initiatives_page.py, test_data/our_initiatives_page_data.py, test_data/urls.py, tests/test_our_initiatives_page_ow6.py
AT:
https://trello.com/c/Z3m8y5F2/1690-at010010101-our-initiatives-verify-the-presence-of-our-initiatives-section
https://trello.com/c/wCjjOBxD/1692-at010010202-our-initiatives-verify-the-functionality-of-our-initiatives-section
https://trello.com/c/UjcTBmiP/1691-at0100208-our-initiatives-student-initiative-verify-the-visibility-of-faq-question-titles
https://trello.com/c/3oCP9PiH/1510-at0100209-our-initiatives-student-initiative-verify-the-clickability-of-faq-question-titles
=> RF_Final | Ducktales | Our_initiatives_page | Stanislav_Osipov

locators/locators.py, pages/for_business_page.py, test_data/urls.py, tests/test_for_business_page_ow6.py
AT:
https://trello.com/c/6ISFI6ha/1460-at0120104-for-business-products-verify-the-headings-are-present-on-the-page
https://trello.com/c/MdJPiIvc/1346-at0120106-for-business-products-verify-the-buttons-are-presented-on-the-page
https://trello.com/c/rKpZFaEc/1345-at0120107-for-business-products-verify-the-elements-are-presented-on-the-page
https://trello.com/c/9NzwUJxW/1338-at0120108-for-business-products-verify-that-the-elements-presented-on-the-page-are-clickable
=> RF_Final | Group_future_qa | Stanislav_Osipov

tests/test_group_100000/pages/main_page.py, tests/test_group_100000/tests/test_main_page_100.py
=> RF_AT_003.14.02 | Footer > Cookies management module > Verify that the 'Manage cookies’ link redirects to Cookies settings page

locators/locators.py, pages/api_page.py, pages/main_page.py, tests/test_api_page_ow6.py, tests/test_main_page_ow6.py
https://trello.com/c/DhPAK4d5
https://trello.com/c/tROnJWlz
https://trello.com/c/crYoHGQQ
https://trello.com/c/fXeRAIQu
=> RF_Final | Group_100000 | E_Kreis

locators/locators.py, pages/sign_in_page.py, tests/test_sign_in_page_ow6.py
TC_014.01.01 https://trello.com/c/MNoY8qKU/1518-tc0140101-sign-in-visibility-structure-verify-of-the-sign-in-form-title-display
TC_014.01.02 https://trello.com/c/7OFMHaFl/1517-tc0140102-sign-in-visibility-structure-verify-of-the-enter-email-field-display
TC_014.01.03 https://trello.com/c/pBMlyVSa/1515-tc0140103-sign-in-visibility-structure-verify-of-the-password-field-display
TC_014.01.05 https://trello.com/c/weIJh17E/1329-tc0140105-sign-in-visibility-structure-verify-of-the-displaying-remember-me-record
TC_014.01.06 https://trello.com/c/tTwBqDzW/1327-tc0140106-sign-in-visibility-structure-verify-of-the-displaying-of-checkbox
TC_014.01.07 https://trello.com/c/Ord1ybP8/1100-tc0140107-sign-in-visibility-structure-verify-of-the-button-submit-display
TC_014.01.08 …
=> RF_Final | group_bugs_in_each_step | Tatsiana_Karnilava

locators/locators.py, pages/main_page.py, test_data/main_page_data.py, tests/test_main_page_ow6.py
1) https://trello.com/c/DPHqKoyE/1288-tc0010101-main-page-search-city-widget-verify-requested-city-name-displayed-on-widget-by-zip-search
2) https://trello.com/c/ntp5oLcl/58-tc0010102-main-page-search-city-widget-search-city-verify-dropdown-options-contain-valid-value
3) https://trello.com/c/EFEzNawo/1282-tc001020401-main-page-search-city-widget-verify-the-buttons-for-metric-and-imperial-are-visible-and-clickable
4) https://trello.com/c/AurJTNtd/260-tc0010403-main-page-search-city-widget-8-day-forecast-verify-in-day-list-first-element-day-by-week
5) https://trello.com/c/pjX2stZ3/261-tc0010404-main-page-search-city-widget-8-day-forecast-verify-in-day-list-first-element-month
6) https://trello.com/c/njTWXkcN/267-tc0010407-main-page-search-city-widget-8-day-forecast-verify-in-day-list-element …
=> RF_Final_group_ducktales_main_page

locators/locators.py, pages/about_us_page.py, pages/partners_page.py, test_data/urls.py, tests/test_about_us_page_ow6.py, tests/test_partners_page_ow6.py
https://trello.com/c/uIFWHQFs
https://trello.com/c/oKkTRHsO
https://trello.com/c/sxIQs46D
https://trello.com/c/XNRvyAGQ
https://trello.com/c/a51AiRnx
=> RF_Final | Group_future_qa | Galina Danilova

locators/locators.py, pages/widgets_constructor_page.py, tests/test_widgets_constructor_page_ow6.py
=> Add: test_tc_001_09_03_verify_visibility_of_celsius

locators/locators.py, test_data/urls.py, tests/test_partners_page_ow6.py
=> RF Final | group python qa| Landau Yevgeniya

locators/locators.py, tests/test_marketplace_page_ow6.py
=> ERR Fix - move locators to marketplace class

tests/test_group_100000/locators/api_page_locators.py, tests/test_group_100000/pages/api_page.py, tests/test_group_100000/tests/test_api_page_100.py
=> add test_TC_001_12_06_Verify that drizzle group of codes contains more than 1 item

tests/test_group_lutz_squad/pages/guide_page.py, tests/test_group_lutz_squad/test_data/data.py, tests/test_group_lutz_squad/tests/test_guide_page.py
https://trello.com/c/aSxQkO6T/592-at0040606-guide-open-weather-products-link-one-call-api-by-call-has-correct-color
=> TC_004.06.06 | Guide > Open weather products > Link 'One Call API by call' has correct color

api_testing/tests/test_validator.py, api_testing/utils/schemas/list_users.json, api_testing/utils/schemas/single_user.json, api_testing/utils/validator.py, requirements.txt
add: jsonschema~=4.17.3 to requirements.txt
=> add: validator method, test version.

.gitignore, api_testing/tests/test_teachers.py, api_testing/utils/logger.py
=> Add logger.py

locators/locators.py, pages/base_page.py, pages/main_page.py, pages/pricing_page.py, tests/test_main_page_ow6.py, tests/test_pricing_page_ow6.py
https://trello.com/c/ZKeZrBqM
https://trello.com/c/bRm9R50C
=> RF_Final | group_qa_anna_prokhoda | Aleksandra Kozhevnikova

tests/test_sign_in_page_ow6.py
=> At 014.05.01

locators/locators.py, pages/api_page.py, tests/test_api_page_ow6.py
https://trello.com/c/8MZaqqB0
creator autotest @Ksenia_Mish
=> RF_Final_Group_Roma_2

locators/locators.py, pages/main_page.py, pages/weather_conditions_page.py, pages/weather_dashboard_page.py, pages/widgets_constructor_page.py, test_data/urls.py, tests/test_main_page_ow6.py, tests/test_search_result_page_ow6.py, tests/test_weather_conditions_page_ow6.py, tests/test_weather_dashboard_ow6.py, tests/test_widgets_constructor_page_ow6.py
https://trello.com/c/f4xtuyhc
https://trello.com/c/qq3pOeIm
https://trello.com/c/BZjjcROL
https://trello.com/c/zQHUxpNX
https://trello.com/c/wTN05WBr
https://trello.com/c/mrSyjaIg
https://trello.com/c/s7kOlwUw
=> RF_Final_Pandora_Box_ZhandarovA

api_testing/pages/file_handler_page.py, api_testing/tests/test_file_handler.py, api_testing/utils/file_handler.py
add two methods to simplify test file_handler, add indent=4 to write_into_json_file (for JSON format), add allure.steps(for "static" methods)
Please, review!
=> ref: add file_handler_page.py

api_testing/data/endpoints.py, api_testing/tests/test_Vitaly_S.py
add: test_list_users_response_status, test_list_users_json_validation,
test_single_user_response_status,
test_single_user_json_validation
=> add: test_list_users_response_status, test_list_users_json_validation,

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py, tests/test_sign_in_page_ow6.py
add test_tc_003_01_03_footer_presence_in_the_dom_tree
ref test_sign_in_page_ow6.py (delete extra lines 4, 5)
=> TC_003.01.03_check_footer_presence_in_the_dom_tree

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/bEkTwdOe/2202-at0030307-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-current-and-forecast-apis-link-visibi
=> AT_003.03.07 Footer > Product Collections module > Visibility, structure, links сlickability > Verify Current and Forecast APIs link visibility

pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/Fzx7mQ2w/2207-at0030310-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-weather-maps-link-visibility
=> AT_003.03.10 Footer > Product Collections module > Visibility, structure, links сlickability > Verify Weather Maps link visibility

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/z1lHU3uc/2208-at0030311-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-widgets-link-visibility
=> AT_003.03.11 Footer > Product Collections module > Visibility, structure, links сlickability > Verify Widgets link visibility

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/UdWg0d8J/2206-at0030308-footer-product-collections-module-visibility-structure-links-%D1%81lickability-verify-historical-weather-data-link-clickabi
=> AT_003.03.08 Footer > Product Collections module > Visibility, structure, links сlickability > Verify Historical Weather Data link clickability

locators/locators.py, pages/main_page.py, test_data/all_links.py, tests/test_main_page_ow6.py
TC_003.06.02
https://trello.com/c/sG89tpTW/976-tc0030602-footer-terms-conditions-module-verify-terms-conditions-module-title-display
TC_003.08.06
https://trello.com/c/qdoNYqXn/1136-tc0030806-footer-single-links-set-links-visibility-and-%D1%81lickability-verify-about-us-link-is-clickable-on-each-page-specified-in
TC_003.12.20
https://trello.com/c/8J1SujMY/945-tc0031220-footer-link-navigation-verify-blog-link-functionality
=> RF_Final | group_future_auto_qa | alena-krauchuk

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py, tests/test_suits_of_pages_ow6.py
https://trello.com/c/26QvGPO4/2219-at0030202-footer-uniform-display-format-verify-display-of-product-collections-module-on-each-page-specified-in-data
=> AT_003.02.02 Footer > Uniform display format > Verify display of Product Collections module on each page specified in Data

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/pqH5e1Es/2220-at0030203-footer-uniform-display-format-verify-display-of-subscription-section-each-page-specified-in-data
=> AT_003.02.03 Footer > Uniform display format > Verify display of Subscription section on each page specified in dataata

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/m3XvD0zb/2221-at0030204-footer-uniform-display-format-verify-display-of-subscription-section-each-page-specified-in-data
=> AT_003.02.04 Footer > Uniform display format > Verify display of Company section on each page specified in Data

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/sEyytCt9/2222-at0030205-footer-uniform-display-format-verify-display-of-technologies-section-on-each-page-specified-in-data
=> AT_003.02.05 Footer > Uniform display format > Verify display of Technologies section on each page specified in Data

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/E0NeVs8C/2223-at0030206-footer-uniform-display-format-verify-display-of-terms-conditions-section-on-each-page-specified-in-data
=> AT_003.02.06 Footer > Uniform display format > Verify display of Terms & Conditions section on each page specified in Data

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/E8MpnBxs/2224-at0030207-footer-uniform-display-format-verify-display-of-single-links-section-on-each-page-specified-in-data
=> AT_003.02.07 Footer > Uniform display format > Verify display of Single links section on each page specified in Data

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/eqWLsgr6/2226-at0030209-footer-uniform-display-format-verify-display-of-social-media-section-on-each-page-specified-in-data
=> AT_003.02.09 Footer > Uniform display format > Verify display of Social media section on each page specified in Data

locators/locators.py, pages/partners_page.py, test_data/urls.py, tests/test_partners_page_ow6.py
https://trello.com/c/23dcruGU/2137-at0111303-partners-and-solutions-python-verify-visibility-and-clickability-of-the-link-view-on-youtube
=> RF_Final | group_future_Auto_QA | Alina M

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/zkf7Kfie/2236-at0030508-footer-subscription-module-visibility-structure-links-%D1%81lickability-verify-display-of-faq-link-on-each-page-specified-i
=> AT_003.05.08 Footer > Subscription module > Visibility, structure, links сlickability > Verify display of FAQ link on each page specified in Data

pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/LhXNhLxe/2238-at0030509-footer-subscription-module-visibility-structure-links-%D1%81lickability-verify-faq-link-clickability
=> AT_003.05.09 Footer > Subscription module > Visibility, structure, links сlickability > Verify FAQ link clickability

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/zgJBbnbW/2240-at0030604-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-website-terms-and-conditions-link-clicka
=> AT_003.06.04 Footer > Terms & Conditions module > Visibility, structure, links сlickability  > Verify Website terms and conditions link clickability

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/CQjHls6I/2242-at0030605-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-terms-and-conditions-of-sale-link-visibi
=> AT_003.06.05 Footer > Terms & Conditions module > Visibility, structure, links сlickability  > Verify Terms and conditions of sale link visibility

pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/X45Y23ea/2244-at0030606-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-terms-and-conditions-of-sale-link-clicka
=> AT_003.06.06 Footer > Terms & Conditions module > Visibility, structure, links сlickability > Verify Terms and conditions of sale link clickability

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/euoO7PNg/2246-at0030607-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-privacy-policy-link-visibility
=> AT_003.06.07 Footer > Terms & Conditions module > Visibility, structure, links сlickability > Verify Privacy Policy link visibility

locators/locators.py, pages/pricing_page.py, tests/test_pricing_page_ow6.py
add POM test “Subscribe” button from "One Call by Call" subscription plan redirects to Billing-info page
=> AT_008.01.01_Pricing_page_“Subscribe” button from "One Call by Call" subscription plan redirects to Billing_Info page

pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/7xbQUffm/2250-at0030608-footer-terms-conditions-module-visibility-structure-links-%D1%81lickability-verify-privacy-policy-link-clickability
=> AT_003.06.08 Footer > Terms & Conditions module > Visibility, structure, links сlickability > Verify Privacy Policy link clickability

locators/locators.py, pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/qn0wmaDF/2251-at0030702-footer-company-module-verify-company-module-title-display
=> AT_003.07.02 Footer > Company module > Verify Company module title display

pages/main_page.py, tests/test_main_page_ow6.py
https://trello.com/c/qBvjnAQ1/2253-at0030703-footer-company-module-visibility-content-verify-the-text-of-company-module-title
=> AT_003.07.03 Footer > Company module > Visibility, content > Verify the text of Company module title
